class FormConfig(object):
    host_url: str = "https://leakyautofill.github.io"
    login_form: dict = {
        "name": "login",
        "click_ele_id": "username",
        "check_value_list": ["username", "password"],
        "sensitive_value_list": ["password"],
        "simple_page": {
            "self": f"{host_url}/login-self/list.html",
            "parent": f"{host_url}/login/list.html",
        },
        "list_page": {
            "self": {
                "original": f"{host_url}/login-self/original.html",
                "display-none": f"{host_url}/login-self/hidden-css-display.html",
                "visibility-hidden": f"{host_url}/login-self/hidden-css-visibility1.html",
                "visibility-collapse": f"{host_url}/login-self/hidden-css-visibility2.html",
                "opacity-0": f"{host_url}/login-self/hidden-css-opacity.html",
                "cover-overlay": f"{host_url}/login-self/hidden-overlay.html",
                "non-effective-size": f"{host_url}/login-self/hidden-non-effective-size.html",
                "off-screen-placement": f"{host_url}/login-self/hidden-off-screen.html",
                "ancestor-overflow": f"{host_url}/login-self/hidden-overflow.html",
                "hidden-property": f"{host_url}/login-self/hidden-hidden.html",
                "clip-property": f"{host_url}/login-self/hidden-clip.html",
                "clip-path-property": f"{host_url}/login-self/hidden-clippath.html",
                "scale-property": f"{host_url}/login-self/hidden-scale.html",
                "font-size-zero": f"{host_url}/login-self/hidden-font-size-zero.html",
                "content-visibility-property": f"{host_url}/login-self/hidden-content-visibility.html",
                "tiny-size": f"{host_url}/login-self/hidden-tiny-size.html",
            },
            "parent": {
                "original": f"{host_url}/login/original.html",
                "display-none": f"{host_url}/login/hidden-css-display.html",
                "visibility-hidden": f"{host_url}/login/hidden-css-visibility1.html",
                "visibility-collapse": f"{host_url}/login/hidden-css-visibility2.html",
                "opacity-0": f"{host_url}/login/hidden-css-opacity.html",
                "cover-overlay": f"{host_url}/login/hidden-overlay.html",
                # "non-effective-size": f"{host_url}/login/hidden-non-effective-size.html",
                "off-screen-placement": f"{host_url}/login/hidden-off-screen.html",
                "ancestor-overflow": f"{host_url}/login/hidden-overflow.html",
                "hidden-property": f"{host_url}/login/hidden-hidden.html",
                "clip-property": f"{host_url}/login/hidden-clip.html",
                "clip-path-property": f"{host_url}/login/hidden-clippath.html",
                "scale-property": f"{host_url}/login/hidden-scale.html",
                "font-size-zero": f"{host_url}/login/hidden-font-size-zero.html",
                "content-visibility-property": f"{host_url}/login/hidden-content-visibility.html",
                # "tiny-size": f"{host_url}/login/hidden-tiny-size.html",
            },
        },
    }

    pii_form: dict = {
        "name": "pii",
        "click_ele_id": "given-name",
        "check_value_list": [
            "given-name",
            "additional-name",
            "family-name",
            "tel",
            "address-line1",
            "address-line2",
        ],
        "sensitive_value_list": ["tel", "address-line1"],
        "simple_page": {
            "self": f"{host_url}/pii-self/list.html",
            "parent": f"{host_url}/pii/list.html",
        },
        "list_page": {
            "self": {
                "original": f"{host_url}/pii-self/original.html",
                "display-none": f"{host_url}/pii-self/hidden-css-display.html",
                "visibility-hidden": f"{host_url}/pii-self/hidden-css-visibility1.html",
                "visibility-collapse": f"{host_url}/pii-self/hidden-css-visibility2.html",
                "opacity-0": f"{host_url}/pii-self/hidden-css-opacity.html",
                "cover-overlay": f"{host_url}/pii-self/hidden-overlay.html",
                "non-effective-size": f"{host_url}/pii-self/hidden-non-effective-size.html",
                "off-screen-placement": f"{host_url}/pii-self/hidden-off-screen.html",
                "ancestor-overflow": f"{host_url}/pii-self/hidden-overflow.html",
                "hidden-property": f"{host_url}/pii-self/hidden-hidden.html",
                "clip-property": f"{host_url}/pii-self/hidden-clip.html",
                "clip-path-property": f"{host_url}/pii-self/hidden-clippath.html",
                "scale-property": f"{host_url}/pii-self/hidden-scale.html",
                "font-size-zero": f"{host_url}/pii-self/hidden-font-size-zero.html",
                "content-visibility-property": f"{host_url}/pii-self/hidden-content-visibility.html",
                "tiny-size": f"{host_url}/pii-self/hidden-tiny-size.html",
            },
            "parent": {
                "original": f"{host_url}/pii/original.html",
                "display-none": f"{host_url}/pii/hidden-css-display.html",
                "visibility-hidden": f"{host_url}/pii/hidden-css-visibility1.html",
                "visibility-collapse": f"{host_url}/pii/hidden-css-visibility2.html",
                "opacity-0": f"{host_url}/pii/hidden-css-opacity.html",
                "cover-overlay": f"{host_url}/pii/hidden-overlay.html",
                # "non-effective-size": f"{host_url}/pii/hidden-non-effective-size.html",
                "off-screen-placement": f"{host_url}/pii/hidden-off-screen.html",
                "ancestor-overflow": f"{host_url}/pii/hidden-overflow.html",
                "hidden-property": f"{host_url}/pii/hidden-hidden.html",
                "clip-property": f"{host_url}/pii/hidden-clip.html",
                "clip-path-property": f"{host_url}/pii/hidden-clippath.html",
                "scale-property": f"{host_url}/pii/hidden-scale.html",
                "font-size-zero": f"{host_url}/pii/hidden-font-size-zero.html",
                "content-visibility-property": f"{host_url}/pii/hidden-content-visibility.html",
                # "tiny-size": f"{host_url}/pii/hidden-tiny-size.html",
            },
        },
    }

    # This is for Keeper PM, as it only triggers autofill functionality in PII form with email field
    pii_email_form: dict = {
        "name": "pii-email",
        "click_ele_id": "given-name",
        "check_value_list": [
            "given-name",
            "additional-name",
            "family-name",
            "tel",
            "email",
            "address-line1",
            "address-line2",
        ],
        "sensitive_value_list": ["tel", "address-line1"],
        "simple_page": {
            "self": f"{host_url}/pii_email-self/list.html",
            "parent": f"{host_url}/pii_email/list.html",
        },
        "list_page": {
            "self": {
                "original": f"{host_url}/pii_email-self/original.html",
                "display-none": f"{host_url}/pii_email-self/hidden-css-display.html",
                "visibility-hidden": f"{host_url}/pii_email-self/hidden-css-visibility1.html",
                "visibility-collapse": f"{host_url}/pii_email-self/hidden-css-visibility2.html",
                "opacity-0": f"{host_url}/pii_email-self/hidden-css-opacity.html",
                "cover-overlay": f"{host_url}/pii_email-self/hidden-overlay.html",
                "non-effective-size": f"{host_url}/pii_email-self/hidden-non-effective-size.html",
                "off-screen-placement": f"{host_url}/pii_email-self/hidden-off-screen.html",
                "ancestor-overflow": f"{host_url}/pii_email-self/hidden-overflow.html",
                "hidden-property": f"{host_url}/pii_email-self/hidden-hidden.html",
                "clip-property": f"{host_url}/pii_email-self/hidden-clip.html",
                "clip-path-property": f"{host_url}/pii_email-self/hidden-clippath.html",
                "scale-property": f"{host_url}/pii_email-self/hidden-scale.html",
                "font-size-zero": f"{host_url}/pii_email-self/hidden-font-size-zero.html",
                "content-visibility-property": f"{host_url}/pii_email-self/hidden-content-visibility.html",
                "tiny-size": f"{host_url}/pii_email-self/hidden-tiny-size.html",
            },
            "parent": {
                "original": f"{host_url}/pii_email/original.html",
                "display-none": f"{host_url}/pii_email/hidden-css-display.html",
                "visibility-hidden": f"{host_url}/pii_email/hidden-css-visibility1.html",
                "visibility-collapse": f"{host_url}/pii_email/hidden-css-visibility2.html",
                "opacity-0": f"{host_url}/pii_email/hidden-css-opacity.html",
                "cover-overlay": f"{host_url}/pii_email/hidden-overlay.html",
                # "non-effective-size": f"{host_url}/pii_email/hidden-non-effective-size.html",
                "off-screen-placement": f"{host_url}/pii_email/hidden-off-screen.html",
                "ancestor-overflow": f"{host_url}/pii_email/hidden-overflow.html",
                "hidden-property": f"{host_url}/pii_email/hidden-hidden.html",
                "clip-property": f"{host_url}/pii_email/hidden-clip.html",
                "clip-path-property": f"{host_url}/pii_email/hidden-clippath.html",
                "scale-property": f"{host_url}/pii_email/hidden-scale.html",
                "font-size-zero": f"{host_url}/pii_email/hidden-font-size-zero.html",
                "content-visibility-property": f"{host_url}/pii_email/hidden-content-visibility.html",
                # "tiny-size": f"{host_url}/pii_email/hidden-tiny-size.html",
            },
        },
    }

    cvv_form: dict = {
        "name": "cvv",
        "click_ele_id": "cc-name",
        "check_value_list": ["cc-name", "cc-number"],
        "sensitive_value_list": ["cc-number"],
        "simple_page": {
            "self": f"{host_url}/cvv-self/list.html",
            "parent": f"{host_url}/cvv/list.html",
        },
        "list_page": {
            "self": {
                "original": f"{host_url}/cvv-self/original.html",
                "display-none": f"{host_url}/cvv-self/hidden-css-display.html",
                "visibility-hidden": f"{host_url}/cvv-self/hidden-css-visibility1.html",
                "visibility-collapse": f"{host_url}/cvv-self/hidden-css-visibility2.html",
                "opacity-0": f"{host_url}/cvv-self/hidden-css-opacity.html",
                "cover-overlay": f"{host_url}/cvv-self/hidden-overlay.html",
                "non-effective-size": f"{host_url}/cvv-self/hidden-non-effective-size.html",
                "off-screen-placement": f"{host_url}/cvv-self/hidden-off-screen.html",
                "ancestor-overflow": f"{host_url}/cvv-self/hidden-overflow.html",
                "hidden-property": f"{host_url}/cvv-self/hidden-hidden.html",
                "clip-property": f"{host_url}/cvv-self/hidden-clip.html",
                "clip-path-property": f"{host_url}/cvv-self/hidden-clippath.html",
                "scale-property": f"{host_url}/cvv-self/hidden-scale.html",
                "font-size-zero": f"{host_url}/cvv-self/hidden-font-size-zero.html",
                "content-visibility-property": f"{host_url}/cvv-self/hidden-content-visibility.html",
                "tiny-size": f"{host_url}/cvv-self/hidden-tiny-size.html",
            },
            "parent": {
                "original": f"{host_url}/cvv/original.html",
                "display-none": f"{host_url}/cvv/hidden-css-display.html",
                "visibility-hidden": f"{host_url}/cvv/hidden-css-visibility1.html",
                "visibility-collapse": f"{host_url}/cvv/hidden-css-visibility2.html",
                "opacity-0": f"{host_url}/cvv/hidden-css-opacity.html",
                "cover-overlay": f"{host_url}/cvv/hidden-overlay.html",
                # "non-effective-size": f"{host_url}/cvv/hidden-non-effective-size.html",
                "off-screen-placement": f"{host_url}/cvv/hidden-off-screen.html",
                "ancestor-overflow": f"{host_url}/cvv/hidden-overflow.html",
                "hidden-property": f"{host_url}/cvv/hidden-hidden.html",
                "clip-property": f"{host_url}/cvv/hidden-clip.html",
                "clip-path-property": f"{host_url}/cvv/hidden-clippath.html",
                "scale-property": f"{host_url}/cvv/hidden-scale.html",
                "font-size-zero": f"{host_url}/cvv/hidden-font-size-zero.html",
                "content-visibility-property": f"{host_url}/cvv/hidden-content-visibility.html",
                # "tiny-size": f"{host_url}/cvv/hidden-tiny-size.html",
            },
        },
    }

    form_dict: dict = {
        "login": login_form,
        "pii": pii_form,
        "pii-email": pii_email_form,
        "cvv": cvv_form,
        "empty": {},
    }

    # return properties of targeted password manager
    def get_form_properties(form_name: str) -> dict:
        if form_name in FormConfig.form_dict:
            return FormConfig.form_dict[form_name]
        else:
            return FormConfig.form_dict["empty"]
